// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Jumia_Clone.Entities;


namespace Jumia_Clone.Models.Entities
{
    public partial interface IApplicationDbContextProcedures
    {
        Task<List<create_orderResult>> create_orderAsync(int? p_customer_id, int? p_address_id, int? p_coupon_id, string p_payment_method, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<update_trending_productsResult>> update_trending_productsAsync(string time_period, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
